//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASPDatabaseFirstEntities : DbContext
    {
        public ASPDatabaseFirstEntities()
            : base("name=ASPDatabaseFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentEmployee> StudentEmployees { get; set; }
        public virtual DbSet<ViewEmployee> ViewEmployees { get; set; }

        public System.Data.Entity.DbSet<WebApplication3.Models.EntityModel.NewTable> NewTables { get; set; }

        public virtual ObjectResult<TestEmployeesViews_Result> TestEmployeesViews(string searchForEmployee) {
            var searchForEmployeeParameter = searchForEmployee != null ?
                new ObjectParameter("SearchForEmployee", searchForEmployee) :
                new ObjectParameter("SearchForEmployee", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestEmployeesViews_Result>("TestEmployeesViews", searchForEmployeeParameter);
        }

      
    }
}
