//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person
    {
        public Person()
        {
            this.Employees = new HashSet<Employee>();
            this.Students = new HashSet<Student>();
            this.NewTables = new HashSet<NewTable>();

        }
    
        public int PersonID { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Date Of Birth")]
        public System.DateTime DateOfBirth { get; set; }
        [DataType(DataType.MultilineText)]
        
        public string Address { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<NewTable> NewTables { get; set; }

    }
}
